services:
    tactics_crsv:
        field_updater_manager:
            class: Tactics\CrsvBundle\FieldUpdaterManager\FieldUpdaterManager
            arguments:
                - '@tactics_crsv.short_name_strategy'
        short_name_strategy:
            class: Tactics\CrsvBundle\NamingStrategy\ShortNameStrategy

