services:
    tactics_crsv.object_updater:
        class: Tactics\FenixBundle\CrsVereniging\ObjectUpdater\ObjectUpdater
        arguments:
            - '@tactics_crsv.short_name_strategy'
    tactics_crsv.short_name_strategy:
        class: Tactics\FenixBundle\CrsVereniging\NamingStrategy\ShortNameStrategy

