services:
    tactics_crsv.object_updater:
        class: Tactics\CrsvBundle\ObjectUpdater\ObjectUpdater
        arguments:
            - '@tactics_crsv.short_name_strategy'
    tactics_crsv.short_name_strategy:
        class: Tactics\CrsvBundle\NamingStrategy\ShortNameStrategy

